imports

In [148]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.autograd import Variable


In [150]:
input_size=2
print(torch.cuda.is_available())

False


training and output data

In [82]:
training_data = Variable(torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]]))
target_data = Variable(torch.FloatTensor([[0],[1],[1],[0]]))
print(training_data,target_data)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]) tensor([[0.],
        [1.],
        [1.],
        [0.]])


Neural Network

In [216]:
model = nn.Sequential(
    nn.Linear(input_size,100,True),
    nn.Sigmoid(),
    #nn.Dropout(0.3),
    nn.Linear(100, 1),
    nn.Sigmoid()
)


In [217]:
loss_fn = nn.MSELoss()
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [218]:
for i in range(1500):
    optimizer.zero_grad()  
    pred = model(training_data)
    loss = loss_fn(pred,target_data)
    print(i, loss.item())
    loss.backward()
    optimizer.step()
    


0 0.2733875513076782
1 0.27302616834640503
2 0.2726670801639557
3 0.27231037616729736
4 0.2719561457633972
5 0.27160435914993286
6 0.27125513553619385
7 0.2709084749221802
8 0.270564466714859
9 0.2702232003211975
10 0.2698846757411957
11 0.2695489525794983
12 0.2692160904407501
13 0.2688860595226288
14 0.2685590088367462
15 0.2682349681854248
16 0.26791390776634216
17 0.26759591698646545
18 0.26728105545043945
19 0.26696932315826416
20 0.2666606903076172
21 0.26635536551475525
22 0.2660531997680664
23 0.2657543420791626
24 0.26545876264572144
25 0.26516643166542053
26 0.2648774981498718
27 0.26459190249443054
28 0.26430970430374146
29 0.2640308439731598
30 0.2637554407119751
31 0.2634834051132202
32 0.2632147967815399
33 0.262949675321579
34 0.26268795132637024
35 0.26242974400520325
36 0.26217490434646606
37 0.26192358136177063
38 0.26167571544647217
39 0.2614312767982483
40 0.2611902952194214
41 0.26095280051231384
42 0.2607187032699585
43 0.2604881227016449
44 0.2602609395980835
45 

241 0.2500038743019104
242 0.25000301003456116
243 0.2500021755695343
244 0.25000134110450745
245 0.2500004768371582
246 0.24999971687793732
247 0.24999891221523285
248 0.24999812245368958
249 0.2499973177909851
250 0.24999657273292542
251 0.24999579787254333
252 0.24999505281448364
253 0.24999430775642395
254 0.24999356269836426
255 0.24999283254146576
256 0.24999210238456726
257 0.24999135732650757
258 0.24999068677425385
259 0.24998995661735535
260 0.24998924136161804
261 0.24998854100704193
262 0.24998785555362701
263 0.2499871551990509
264 0.249986469745636
265 0.2499857395887375
266 0.24998508393764496
267 0.24998441338539124
268 0.24998371303081512
269 0.2499830573797226
270 0.24998238682746887
271 0.24998167157173157
272 0.24998101592063904
273 0.2499803602695465
274 0.2499796748161316
275 0.24997903406620026
276 0.24997837841510773
277 0.249977707862854
278 0.24997703731060028
279 0.24997639656066895
280 0.24997572600841522
281 0.2499750852584839
282 0.24997442960739136
283 0.

456 0.24985456466674805
457 0.24985381960868835
458 0.24985308945178986
459 0.24985234439373016
460 0.24985159933567047
461 0.24985086917877197
462 0.2498500943183899
463 0.2498493641614914
464 0.2498486042022705
465 0.2498478889465332
466 0.24984712898731232
467 0.24984638392925262
468 0.24984565377235413
469 0.24984489381313324
470 0.24984413385391235
471 0.24984340369701385
472 0.24984264373779297
473 0.24984189867973328
474 0.24984115362167358
475 0.2498403936624527
476 0.2498396337032318
477 0.24983888864517212
478 0.24983814358711243
479 0.24983736872673035
480 0.24983662366867065
481 0.24983587861061096
482 0.24983513355255127
483 0.249834343791008
484 0.2498335838317871
485 0.2498328685760498
486 0.24983210861682892
487 0.24983133375644684
488 0.24983058869838715
489 0.24982981383800507
490 0.24982906877994537
491 0.2498282790184021
492 0.2498275190591812
493 0.24982677400112152
494 0.24982598423957825
495 0.24982523918151855
496 0.24982449412345886
497 0.24982371926307678
498 

692 0.24966314435005188
693 0.24966222047805786
694 0.2496613711118698
695 0.24966049194335938
696 0.24965958297252655
697 0.24965868890285492
698 0.24965782463550568
699 0.24965694546699524
700 0.24965602159500122
701 0.2496551275253296
702 0.24965426325798035
703 0.2496533840894699
704 0.24965249001979828
705 0.24965158104896545
706 0.24965068697929382
707 0.2496497929096222
708 0.24964891374111176
709 0.24964801967144012
710 0.2496471256017685
711 0.24964624643325806
712 0.24964530766010284
713 0.2496444284915924
714 0.24964351952075958
715 0.24964264035224915
716 0.24964170157909393
717 0.2496408224105835
718 0.24963994324207306
719 0.24963906407356262
720 0.2496381253004074
721 0.24963723123073578
722 0.24963630735874176
723 0.24963544309139252
724 0.2496345043182373
725 0.24963361024856567
726 0.24963270127773285
727 0.24963180720806122
728 0.2496308833360672
729 0.24962995946407318
730 0.24962906539440155
731 0.24962817132472992
732 0.2496272772550583
733 0.24962635338306427
734

 0.24946220219135284
903 0.24946115911006927
904 0.2494601160287857
905 0.24945907294750214
906 0.24945802986621857
907 0.24945701658725739
908 0.24945597350597382
909 0.24945493042469025
910 0.24945390224456787
911 0.2494528442621231
912 0.24945181608200073
913 0.24945078790187836
914 0.2494497001171112
915 0.24944865703582764
916 0.24944761395454407
917 0.2494465708732605
918 0.24944552779197693
919 0.24944446980953217
920 0.2494434267282486
921 0.24944238364696503
922 0.24944131076335907
923 0.2494402825832367
924 0.24943920969963074
925 0.24943815171718597
926 0.2494370937347412
927 0.24943603575229645
928 0.24943499267101288
929 0.24943393468856812
930 0.24943287670612335
931 0.2494318187236786
932 0.24943074584007263
933 0.24942967295646667
934 0.2494286298751831
935 0.24942752718925476
936 0.2494264841079712
937 0.24942542612552643
938 0.24942438304424286
939 0.2494233250617981
940 0.24942225217819214
941 0.2494211494922638
942 0.24942012131214142
943 0.24941901862621307
944 0.2


1098 0.24924184381961823
1099 0.2492406666278839
1100 0.24923941493034363
1101 0.24923817813396454
1102 0.24923697113990784
1103 0.24923574924468994
1104 0.24923454225063324
1105 0.24923332035541534
1106 0.24923205375671387
1107 0.24923083186149597
1108 0.24922959506511688
1109 0.249228373169899
1110 0.2492271363735199
1111 0.24922588467597961
1112 0.24922466278076172
1113 0.24922339618206024
1114 0.24922218918800354
1115 0.24922092258930206
1116 0.24921971559524536
1117 0.24921846389770508
1118 0.2492172122001648
1119 0.2492159754037857
1120 0.24921472370624542
1121 0.24921347200870514
1122 0.24921223521232605
1123 0.24921096861362457
1124 0.2492097169160843
1125 0.2492084950208664
1126 0.2492072433233261
1127 0.24920597672462463
1128 0.24920473992824554
1129 0.24920347332954407
1130 0.2492022067308426
1131 0.2492009401321411
1132 0.24919968843460083
1133 0.24919842183589935
1134 0.24919718503952026
1135 0.2491959184408188
1136 0.2491946518421173
1137 0.24919337034225464
1138 0.24919

1284 0.24899370968341827
1285 0.24899223446846008
1286 0.24899080395698547
1287 0.24898934364318848
1288 0.24898786842823029
1289 0.2489863932132721
1290 0.2489849478006363
1291 0.2489834874868393
1292 0.2489819973707199
1293 0.2489805370569229
1294 0.2489790916442871
1295 0.24897760152816772
1296 0.24897608160972595
1297 0.24897463619709015
1298 0.24897314608097076
1299 0.24897167086601257
1300 0.24897019565105438
1301 0.2489687204360962
1302 0.2489672303199768
1303 0.24896572530269623
1304 0.24896425008773804
1305 0.24896274507045746
1306 0.24896128475666046
1307 0.2489597648382187
1308 0.2489582896232605
1309 0.24895678460597992
1310 0.24895529448986053
1311 0.24895380437374115
1312 0.24895229935646057
1313 0.2489507794380188
1314 0.24894928932189941
1315 0.24894776940345764
1316 0.24894626438617706
1317 0.24894478917121887
1318 0.2489432394504547
1319 0.24894174933433533
1320 0.24894024431705475
1321 0.24893872439861298
1322 0.2489372044801712
1323 0.24893568456172943
1324 0.248934

1421 0.24877895414829254
1422 0.24877728521823883
1423 0.24877560138702393
1424 0.24877388775348663
1425 0.24877221882343292
1426 0.24877053499221802
1427 0.2487688511610031
1428 0.24876713752746582
1429 0.24876545369625092
1430 0.24876374006271362
1431 0.24876202642917633
1432 0.24876032769680023
1433 0.24875859916210175
1434 0.24875690042972565
1435 0.24875517189502716
1436 0.24875347316265106
1437 0.24875175952911377
1438 0.24875004589557648
1439 0.24874833226203918
1440 0.2487466037273407
1441 0.2487448751926422
1442 0.2487431764602661
1443 0.24874143302440643
1444 0.24873973429203033
1445 0.24873797595500946
1446 0.24873626232147217
1447 0.24873453378677368
1448 0.248732790350914
1449 0.2487310767173767
1450 0.24872934818267822
1451 0.24872758984565735
1452 0.24872584640979767
1453 0.24872411787509918
1454 0.24872234463691711
1455 0.24872060120105743
1456 0.24871887266635895
1457 0.24871712923049927
1458 0.248715341091156
1459 0.24871359765529633
1460 0.24871185421943665
1461 0.24

In [208]:
print(model(torch.FloatTensor([[0,0]])))
print(pred)

tensor([[0.4310]], grad_fn=<SigmoidBackward>)
tensor([[0.4310],
        [0.4946],
        [0.4726],
        [0.5193]], grad_fn=<SigmoidBackward>)
